### ISSUE TITLE
USER STORY: View products

### ISSUE THREAD

**Issue by mittnamnkenny** [mittnamnkenny/galleriet#11]
As a **Site Shopper** I can **view a list of products** so that **I can select some to purchase**

## Acceptance Criteria

- User is presented with a list of products for sale
- Correct image and information for each product

## Tasks

- [x] Complete database model for products
- [x] Create products list page
- [x] Test the completed functionality
