### ISSUE TITLE
USER STORY: Product detail

### ISSUE THREAD

**Issue by mittnamnkenny** [mittnamnkenny/galleriet#12]
As a **Site Shopper** I can **view individual product details** so that **I can identify the price, description, product image etc**

## Acceptance Criteria

- User should be able to click on a product for full information
- Correct image and information is presented to the user

## Tasks

- [x] Complete database model for products
- [x] Create product detail page
- [x] Test the completed functionality
