### ISSUE TITLE
USER STORY: View total

### ISSUE THREAD

**Issue by mittnamnkenny** [mittnamnkenny/galleriet#13]
As a **Site Shopper** I can **easily view the total of my purchase at any time** so that **I can avoid spending too much**

## Acceptance Criteria

- Grand Total is always visible to the user
- Grand Total is automatically updated when adding new products to the bag

## Tasks

- [x] Create add to bag functionality
- [x] Create code to display grand total to user
- [x] Test the completed functionality
