### ISSUE TITLE
USER STORY: Sort list

### ISSUE THREAD

**Issue by mittnamnkenny** [mittnamnkenny/galleriet#14]
As a **Site Shopper** I can **sort the list of available products** so that **I can easily identify the best priced and categorically sorted products**

## Acceptance Criteria

- User should be able to sort by price
- User should be able to sort by category
- User should be able to sort by name

## Tasks

- [x] Create sort select box on product list page
- [x] Create code to automatically return sorted products
- [x] Test the completed functionality
