### ISSUE TITLE
USER STORY: Search product

### ISSUE THREAD

**Issue by mittnamnkenny** [mittnamnkenny/galleriet#15]
As a **Site Shopper** I can **search for a product** so that **I can find a specific product I’d like to purchase**

## Acceptance Criteria

- The search field is easily accessible to the user
- User can search for products by name and description
- User can easily see what they’ve searched for and the number of results

## Tasks

- [x] Create search field that is easily accessible to the user
- [x] Create search functionality to return total products based on name and description
- [x] Test the completed functionality
