### ISSUE TITLE
USER STORY: System messages

### ISSUE THREAD

**Issue by mittnamnkenny** [mittnamnkenny/galleriet#16]
As a **Site User** I will **get system messages when I interact with the site** so that **I get feedback when certain actions are completed**

## Acceptance Criteria

- User should get feedback through pop-up messages with relevant information
- The pop-up message should include a close button

## Tasks

- [x] Create code to display pop-up messages with relevant information to the user
- [x] Create close button to remove the pop-up message
- [x] Test the completed functionality
