### ISSUE TITLE
USER STORY: Product purchase

### ISSUE THREAD

**Issue by mittnamnkenny** [mittnamnkenny/galleriet#18]
As a **Site Shopper** I can **easily select a product to purchase** so that **I can continue browsing the site and viewing more products**

## Acceptance Criteria

- User should be able to add a product to the shopping bag on the product details page
- Adding a product will automatically update the shopping bag and grand total

## Tasks

- [ ] Create add to bag link and functionality
- [ ] Create shopping bag page and link to access it
- [ ] Test the completed functionality
