### ISSUE TITLE
USER STORY: Shopping bag

### ISSUE THREAD

**Issue by mittnamnkenny** [mittnamnkenny/galleriet#19]
As a **Site Shopper** I can **view items in my bag to be purchased** so that **I can identify the total cost of my purchase and all items I will receive**

## Acceptance Criteria

- User should be able to view the shopping bag and all products added
- User should be able to remove products and update their shopping bag
- User should be able to view the grand total before proceeding to the checkout page

## Tasks

- [ ] Create shopping bag page and link to access it
- [ ] Create code to display all added products with grand total
- [ ] Create remove product functionality on the shopping bag page
- [ ] Test the completed functionality
