### ISSUE TITLE
USER STORY: Add products

### ISSUE THREAD

**Issue by mittnamnkenny** [mittnamnkenny/galleriet#2]
As a **Site Admin** I can **add products directly from the site** so that **I can add new items to my store**

## Acceptance Criteria

- Site admin can add products directly from the site
- Site admin can upload an product image

## Tasks

- [x] Create add a new product page restricted to admin user only
- [x] Create form with required fields to add new product to database
- [x] Create link to access add a new product
- [x] Test the completed functionality
