### ISSUE TITLE
USER STORY: Payment

### ISSUE THREAD

**Issue by mittnamnkenny** [mittnamnkenny/galleriet#20]
As a **Site Shopper** I can **easily enter my payment information** so that **I can check out quickly with no hassles, and feel that my personal and payment information is safe and secure**

## Acceptance Criteria

- User shipping and payment information is required on the checkout page
- An order summary is presented to the user with grand total
- Stripe is used for safe and secure payments

## Tasks

- [ ] Create checkout page and link to access it
- [ ] Create user delivery / payment form
- [ ] Set up Stripe API for safe and secure payments
- [ ] Test the completed functionality
