### ISSUE TITLE
USER STORY: Order confirmation

### ISSUE THREAD

**Issue by mittnamnkenny** [mittnamnkenny/galleriet#21]
As a **Site Shopper** I can **view an order confirmation after checkout** so that **I can verify that my purchase was successful and I haven’t made any mistakes**

## Acceptance Criteria

- User is presented with full order information after checkout
- User should receive an confirmation email including full order information

## Tasks

- [x] Create order confirmation page that user is redirected to after successful purchase
- [x] Create functionality to send automatic email confirmation to user after successful purchase
- [x] Test the completed functionality
