### ISSUE TITLE
USER STORY: Contact page

### ISSUE THREAD

**Issue by mittnamnkenny** [mittnamnkenny/galleriet#23]
As a **Site User** I can **contact site admin** so that **I can get my questions answered or provide feedback**

## Acceptance Criteria

- User should easily be able to contact store admin
- User should be presented with an contact form

## Tasks

- [x] Create contact page and link to access it
- [x] Create contact form with required fields
- [x] Test the completed functionality
