### ISSUE TITLE
USER STORY: Newsletter

### ISSUE THREAD

**Issue by mittnamnkenny** [mittnamnkenny/galleriet#24]
As a **Site User** I can **subscribe to a newsletter** so that **I can get email informing me about new products and any changes made to the site**

## Acceptance Criteria

- User should be able to subscribe to a newsletter
- Should be easily accessible to the user

## Tasks

- [x] Create mailchimp account
- [x] Create subscribe form easily accessible to the user
- [x] Test the completed functionality
