### ISSUE TITLE
USER STORY: Facebook page

### ISSUE THREAD

**Issue by mittnamnkenny** [mittnamnkenny/galleriet#25]
As a **Site User** I can **access the store’s Facebook business page** so that **I can view posts and updates made on Facebook and interact**

## Acceptance Criteria

- Provide a link in the footer using matching Font Awesome Facebook icon
- The link should open in a new tab

## Tasks

- [x] Create Facebook business page
- [x] Create link to access the Facebook business page
- [x] Test that the link opens in new tab and that the address is correct
