### ISSUE TITLE
USER STORY: SEO

### ISSUE THREAD

**Issue by mittnamnkenny** [mittnamnkenny/galleriet#26]
As a **Site User** I can **easily find the site using popular search engines** so that **I can take advantage of what the site has to offer**

## Acceptance Criteria

- Implement Keywords and descriptive meta tags
- robots.txt file
- sitemap.xml file

## Tasks

- [x] Use wordtracker to research and implement keywords
- [x] Create robots.txt file
- [x] Create sitemap.xml file
- [x] Test that all is correct
