### ISSUE TITLE
USER STORY: Update products

### ISSUE THREAD

**Issue by mittnamnkenny** [mittnamnkenny/galleriet#3]
As a **Site Admin** I can **update products directly from the site** so that **I can change product prices, descriptions, images, and other product criteria**

## Acceptance Criteria

- Site admin can update products directly from the site
- Site admin can upload and update an product image

## Tasks

- [x] Create edit a product page restricted to admin user only
- [x] Create form with fields pre-populated for admin to update product in database
- [x] Create link to access update product
- [x] Test the completed functionality
