### ISSUE TITLE
USER STORY: 404 page

### ISSUE THREAD

**Issue by mittnamnkenny** [mittnamnkenny/galleriet#32]
As a **Site User** I am **presented with a custom 404 page when trying to access a URL that does not exist** so that **I can get an proper error page and easily return to the home page**

## Acceptance Criteria

- The custom 404 page should be matching the overall design of the site
- User should be provided a link to the home page

## Tasks

- [x] Create code to display a custom 404 page
- [x] Include a home link on the 404 page
- [x] Test the completed functionality
