### ISSUE TITLE
USER STORY: Delete products

### ISSUE THREAD

**Issue by mittnamnkenny** [mittnamnkenny/galleriet#4]
As a **Site Admin** I can **delete products directly from the site** so that **I remove items that are no longer for sale**

## Acceptance Criteria

- Site admin can delete products directly from the site
- Site admin should have to confirm before deleting a product

## Tasks

- [x] Create delete a product page or modal restricted to admin user only
- [x] Create link to access delete product
- [x] Test the completed functionality
