### ISSUE TITLE
USER STORY: Account registration

### ISSUE THREAD

**Issue by mittnamnkenny** [mittnamnkenny/galleriet#6]
As a **Site User** I can **register an account** so that **I can have a personal account and be able to view my profile**

## Acceptance Criteria

- To register a user must enter username, email and password
- User should not be able to register the same username more than once

## Tasks

- [x] Install allauth library
- [x] Create sign up link and customize page
- [x] Test the completed functionality
