### ISSUE TITLE
USER STORY: Login/Logout

### ISSUE THREAD

**Issue by mittnamnkenny** [mittnamnkenny/galleriet#7]
As a **Site User** I can **login or logout** so that **I can access my personal account information**

## Acceptance Criteria

- To login a user must enter correct username (or email) and password
- User should have to confirm before logging out of their account

## Tasks

- [x] Create sign in link and customize page
- [x] Create sign out link and customize page
- [x] Test the completed functionality
