### ISSUE TITLE
USER STORY: Password reset

### ISSUE THREAD

**Issue by mittnamnkenny** [mittnamnkenny/galleriet#8]
As a **Site User** I can **easily reset my password in case I forget it** so that **I can recover access to my account**

## Acceptance Criteria

- A Forgot password link should be available on the login page
- User should have to enter their registered email address
- User should receive an password reset email

## Tasks

- [x] Create password reset page and link to access it using the sign in page
- [x] Create send automatic email functionality for password reset to user
- [x] Test the completed functionality
