### ISSUE TITLE
USER STORY: Personalized profile

### ISSUE THREAD

**Issue by mittnamnkenny** [mittnamnkenny/galleriet#9]
As a **Site User** I can **have a personalized profile** so that **I can view my personal order history and order confirmations, and save my payment information**

## Acceptance Criteria

- My Profile link is easily accessible to the user
- User should be able to update and save their default delivery information
- User should be able to view their order history

## Tasks

- [x] Create my profile page and link to access it restricted to logged in users
- [x] Create delivery information form with pre-populated fields that user can update
- [x] Create section that display order history including order confirmation
- [x] Test the completed functionality
